name: clone_whats_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  mobile_number: ^0.0.4
  toast: ^0.1.5
  image_picker: ^0.6.4
  contacts_service: ^0.3.10
  permission_handler: ^5.0.0

  firebase_auth: ^0.14.0+9
  firebase_core: ^0.4.4+3
  firebase_database: ^3.1.3
  firebase_storage: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"


flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"